# Окружение для разработки
---
- hosts: all
  become: yes

  roles:
    - role: ntp
    - role: apt
    - role: ruby-brightbox

- hosts: all
  become: no

  tasks:
    - block:
        - name: Create temp directory
          shell: 'mktemp -d -t redmine.XXXXXXXXXX'
          register: mktemp

        - name: Download redmine archive
          get_url:
            url: 'http://www.redmine.org/releases/redmine-{{ redmine_version }}.tar.gz'
            dest: '{{ mktemp.stdout }}/redmine-{{ redmine_version }}.tar.gz'

        - name: Ensure redmine directory exists
          file:
            path: '{{ redmine_install_dir }}'
            state: directory

        - name: Unpack redmine archive
          unarchive:
            src: '{{ mktemp.stdout }}/redmine-{{ redmine_version }}.tar.gz'
            dest: '{{ redmine_install_dir }}'
            creates: '{{ redmine_install_dir }}'

        - name: Add custom gems
          copy:
            content: '{{ custom_gemfile }}'
            dest: '{{ redmine_install_dir }}/Gemfile.local'

        - name: Bundle install
          bundler:
            state: present
            user_install: yes
            chdir: '{{ redmine_install_dir }}'
            extra_args: '--jobs=4 --without development test sqlite3 mysql2 mysql'
          environment:
            RAILS_ENV: 'production'
          retries: 2
          delay: 10

      always:
        - name: Remove temp directory
          file:
            path: '{{ mktemp.stdout }}'
            state: absent
          when: mktemp is defined
