# apt
- src: https://github.com/vterdunov/ansible-apt
  name: apt

# ntp
- src: https://github.com/geerlingguy/ansible-role-ntp
  name: ntp

# ruby brightbox
- src: https://github.com/vterdunov/ansible-ruby-brightbox
  name: ruby-brightbox

# PostgreSQL
- src: ANXS.postgresql
  name: postgresql

# nginx
- src: https://github.com/jdauphant/ansible-role-nginx
  name: nginx
